[project]
name = "koja-diffuser"
version = "0.1.0"
description = ""
requires-python = ">=3.13,<3.14"
dependencies = [
    "datasets>=4.8.5",
    "httpx>=0.28.1",
    "lancedb>=0.30.2",
    "pyarrow<24",
    "streamlit>=1.57.0",
    "tqdm>=4.67.3",
    "typer>=0.25.1",
    "torch",
    "torchvision",
    "jaxtyping>=0.3.9",
    "einops>=0.8.2",
    "mlflow>=3.12.0",
    "transformers>=5.8.0",
    "fastapi>=0.136.1",
    "uvicorn>=0.46.0",
    "huggingface-hub>=1.14.0",
]

[project.scripts]
main = "koja_diffuser.typer:app"
stage1 = "koja_diffuser.train.stage1:stage1"
stage2 = "koja_diffuser.train.stage2:stage2"

[dependency-groups]
cu130 = ["torch>=2.11.0", "torchvision>=0.26.0"]

cpu = ["torch>=2.11.0", "torchvision>=0.26.0"]

[tool.uv]
default-groups = ["cu130"]
conflicts = [[{ group = "cpu" }, { group = "cu130" }]]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", group = "cpu" },
    { index = "pytorch-cu130", group = "cu130" },
]

torchvision = [
    { index = "pytorch-cpu", group = "cpu" },
    { index = "pytorch-cu130", group = "cu130" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[build-system]
requires = ["uv_build>=0.11.8,<0.12"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "koja_diffuser"
module-root = ""

[tool.ruff.lint]
ignore = ["F722", "F821"]
